spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: GSJgsj0209
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081